routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//USER & CUSTOMER Route -------------------------------------




Route::group(['middleware' => 'auth'], function () {
    Route::get('/checkout', 'CartController@checkout')->name('checkout');
    Route::post('/checkout/calculateShipping', 'CartController@calculateShipping')->name('calculateShipping');
    Route::get('/payment', 'BillingController@checkout')->name('payment');
    Route::get('/user-profile', 'UserController@editUser')->name('userProfile');
    Route::get('/user-profile-form', 'UserController@userProfile')->name('userProfileForm');
    Route::get('/user-address', 'UserController@userAddress')->name('userAddress');
    Route::get('/user-history', 'UserController@userHistory')->name('userHistory');
    Route::get('/user-confirmPayment', 'UserController@userConfirmPayment')->name('userConfirmPayment');
    Route::post('/user-confirmPayment/detail', 'UserController@userDetailPayment')->name('userDetailPayment');
    Route::post('/user-confirmPayment/upload', 'UserController@userUploadPaymentPage')->name('userUploadPaymentPage');
    Route::put('/user-confirmPayment/uploadPaymentFile', 'UserController@uploadPaymentFile')->name('uploadPaymentFile');
    Route::get('/user-wholesale', 'UserController@userWholesale')->name('userWholesale');
    Route::get('/switchwholesale', 'UserController@switchwholesale')->name('switchwholesale');
    Route::put('/profile/updateProfile', 'UserController@updateProfile')->name('updateProfile');
    Route::get('/shop/wholesale', 'ProductController@wholesaleShop')->name('wholesaleShop');
    Route::post('/address/delAddress', 'UserController@delAddress')->name('delAddress');
    Route::post('/address/updateAddress', 'AddressController@updateAddress')->name('updateAddress');
    Route::post('/address/updateAddressSubmit', 'UserController@updateAddressSubmit')->name('updateAddressSubmit');
    Route::get('/user-payment', 'BillingController@userPayment')->name('user-payment');
    Route::post('/user-phoneshipping', 'BillingController@phoneShipping')->name('phoneShipping');
    Route::get('/confirm-order', 'OrderController@confirmOrder')->name('confirm-order');
    Route::get('/finish-order', 'OrderController@finishOrder')->name('finish-order');
    Route::get('/order-succeed', 'OrderController@orderSucceed')->name('order-succeed');

    //mail
    Route::get('/mail/send', 'MailController@invoiceMail');
    Route::get('/mail/test', function () {
        $invoice = App\Invoice::find(1);

        return new App\Mail\InvoicePaid($invoice);
    });

 
});


Route::get('/test/{lastOrder}/{userId}', 'MailController@send');
Route::get('/logout', 'Auth\LoginController@logout')->name('logoutGet');

//ini route yg td nya diluar
Route::get('/', 'HomeController@index')->name('welcome');
Route::get('/activation/{id}', 'UserController@changeStatus')->name('activationUser');
Route::get('/shop', 'ProductController@index')->name('shop');
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/shop_detail/', 'ProductController@index')->name('shop_detail');
Route::get('/category-list', 'CategoryController@index')->name('category-list');
Route::get('/partner-petani', 'SupplierController@index')->name('partner-petani');
Route::get('/blog', 'PostController@index')->name('blog');
Route::get('/blog/{{posts}}', 'PostController@show')->name('blog.show');
//ini route yg td nya diluar
   //ini route yg td nya diluar
   Route::resource('users', 'UserController');
   Route::resource('suppliers', 'SupplierController');
   Route::resource('customers', 'CustomerController');
   Route::resource('carts', 'CartController');
   Route::resource('shippers', 'ShipperController');
   Route::resource('orders', 'OrderController');
   Route::resource('billings', 'BillingController');
   Route::resource('categories', 'CategoryController');
   Route::resource('products', 'ProductController');
   Route::resource('order_details', 'OrderDetailController');
//   Route::resource('products', 'ProductController');
   Route::resource('posts', 'PostController');
   Route::resource('addresses', 'AddressController');
   //ini route yg td nya diluar
   //ini route yg td nya diluar
   Route::post('/cart/addTemp', 'CartController@addCartTemp')->name('addCartTemp');
   Route::post('/cart/delTemp', 'CartController@deleteCartTemp')->name('deleteCartTemp');
   Route::post('/cart/delDetailTemp', 'CartController@deleteCartDetailTemp')->name('deleteCartDetailTemp');
   Route::post('/cart/addQtyTemp', 'CartController@addQtyCartTemp')->name('addQtyCartTemp');


   Route::any('/shop/filterPriceAll', 'ProductController@filterPriceAllProduct')->name('filterPriceAll');
   Route::any('/shop/filterBestOffer', 'ProductController@filterBestOffer')->name('filterBestOffer');
   Route::any('/shop/sortBy', 'ProductController@sortBy')->name('sortBy');
   Route::any('/shop/catSortBy', 'CategoryController@catSortBy')->name('catSortBy');
   Route::any('/shop/searchProduct', 'ProductController@searchProduct')->name('searchProduct');


   Route::get('/our-activities', 'PageController@ourActivities')->name('our-activities');
   Route::get('/about-us', 'PageController@aboutUs')->name('about-us');
   Route::get('/our-team', 'PageController@ourTeam')->name('our-team');
   Route::get('/faq', 'PageController@faq')->name('faq');
   Route::get('/terms-and-condition', 'PageController@termsCondition')->name('terms-and-condition');
   Route::get('/customer-service', 'PageController@customerService')->name('customer-service');


   Route::any('/category/filterPriceCategory', 'CategoryController@filterPriceCategory')->name('filterPriceCategory');
   //ini route yg td nya diluar
//Route::get('/categories', function () {
//    return view('category-list');
//})->name('category-list');

Route::get('/profile', function () {
    return view('profile');
})->name('profile');

Route::get('/our-goals', function () {
    return view('our-goals');
})->name('our-goals');

Route::get('/contact-us', function () {
    return view('contact-us');
})->name('contact-us');

//Route::get('/login', function () {
//    return view('login');
//})->name('login');

//Route::get('/register', function () {
//    return view('register');
//})->name('register');
//
//Route::get('/blog-detail', function () {
//    return view('blog-detail');
//})->name('blog-detail');
//
//Route::get('/cart', function () {
//    return view('cart');
//})->name('cart');
//
//
//Route::get('/checkout', function () {
//    return view('checkout');
//})->name('checkout');

//-------------------------------------------------

//Back Route -------------------------------------



Auth::routes();
Route::group(['middleware' => 'auth'], function () {
    //diisi routes buat halaman user yg harus login dulu
});



//ADMIN ROUTES
Route::get('/admin', 'AdminController@index')->name('admin');
Route::post('/admin/login', 'Auth\AdminLoginController@login')->name('admin.login.submit');
Route::get('/admin/login', 'Auth\AdminLoginController@showLoginForm')->name('admin.login');
Route::group(['middleware' => ['auth:admin']], function () {

    //    Route::get('admin/coupon', 'BillingController@couponAdmin')->name('admin.coupon');

    //manage admin
    Route::get('admin/dashboard', 'AdminController@index')->name('admin.dashboard');
    Route::post('admin/logout', 'Auth\AdminLoginController@logout')->name('admin.logout.submit');
    Route::get('admin/admin_page', 'AdminController@adminPage')->name('admin.admin.page');
    Route::get('admin/configuration', 'AdminController@configurationAdmin')->name('admin.configuration');
    Route::get('admin/admin_page/add', 'AdminController@addAdminPage')->name('admin.add.show');
    Route::get('admin/admin_page/edit/{id}', 'AdminController@edit')->name('admin.edit.show');
    Route::post('admin/admin_page/add', 'AdminController@store')->name('admin.add.submit');
    Route::put('admin/admin_page/edit/{id}', 'AdminController@updateAdmin')->name('admin.update.submit');
    Route::delete('admin/admin_page/{id}', 'AdminController@destroy')->name('admin.delete.submit');

    //manage category
    Route::get('admin/category', 'CategoryController@categoryAdmin')->name('admin.category');
    Route::get('admin/best_categories', 'CategoryController@bestCategoryAdmin')->name('admin.best.categories');
    Route::get('admin/category/add', 'CategoryController@addCategoryAdmin')->name('category.add.show');
    Route::get('admin/category/edit/{id}', 'CategoryController@edit')->name('category.edit.show');
    Route::post('admin/category/add', 'CategoryController@store')->name('category.add.submit');
    Route::put('admin/category/edit/{id}', 'CategoryController@updateCategory')->name('category.update.submit');
    Route::delete('admin/category/delete/{id}', 'CategoryController@destroy')->name('category.delete');

    //manage category post
    Route::get('admin/category_post', 'CategoryPostController@categoryPostAdmin')->name('admin.category.post');
    Route::get('admin/category_post/add', 'CategoryPostController@addCategoryPostAdmin')->name('category_post.add.show');
    Route::get('admin/category_post/edit/{id}', 'CategoryPostController@edit')->name('category_post.edit.show');
    Route::post('admin/category_post/add', 'CategoryPostController@addCategoryPostAdmin')->name('category_post.add.submit');
    Route::put('admin/category_post/edit/{id}', 'CategoryPostController@updateCategoryPost')->name('category_post.update.submit');
    Route::delete('admin/category_post/{id}', 'CategoryPostController@destroy')->name('category_post.delete');

    //manage post

resources/views/404.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: robseptian
 * Date: 05/01/18
 * Time: 19.44
 */
?>
@extends('layouts.app')
@section('content')
    <div id="main">
    <div class="section section-error pt-12 pb-12">
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <div class="text-center">
                        <img src="{{URL::asset('/assets/images/404.png')}}" class="mb-6" alt="" />
                        <h3 class="error-title uppercase">Oops! Halaman ini tidak tersedia</h3>
                        <span class="error-content uppercase">
										Kembali ke
										<a href="{{URL::to('/')}}">Homepage</a>
									</span>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/cartDetail.blade.php
        <div class="cart-totals">
            <table>
                <tbody>
                <tr class="cart-subtotal">
                    <th>Subtotal</th>
                    <td id="loading">Rp. <?php echo Cart::subtotal(); ?></td>
                </tr>
                </tbody>
            </table>
            <div class="proceed-to-checkout" onclick="cartCheck('{{Cart::count()}}')" style="cursor:pointer">
                <a >Lanjut ke Pengiriman</a>
            </div>
        </div>

        <script type="text/javascript">
            $('[data-toggle="tooltip"]').tooltip({
                trigger: 'manual'
            });

            function cartCheck(cart) {
                if (cart > 0) {
                    var url = '{{URL::to('/checkout')}}';
                    window.location.href = url;
                } else {
                    $.toast({
                        heading: 'Error',
                        text: 'Cart Kosong',
                        showHideTransition: 'fade',
                        icon: 'error',
                        hideAfter: 3000,
                        position: 'bottom-center',
                        loader: false,
                    });
                }
            }

        </script>

resources/views/cartbar.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: black
 * Date: 1/17/2018
 * Time: 4:21 PM
 */?>

<div class="mini-cart">
    <div class="mini-cart-icon" data-count="{{ Cart::count() }}">
        <i style="color: #fff;" class="ion-bag"></i>
    </div>
</div>
<div class="widget-shopping-cart-content">
    <ul class="cart-list">
        @if(Cart::content()->count() === 0)
            <p class="text-center">
            <h2 class="text-center section-bg-1">Tidak ada item</h2>
            </p>
        @else
            @foreach($carts as $row)
                <li>
                    <a class="remove" onclick="deleteCartTemp('{{ $row->id }}')"
                       style="cursor: pointer">×</a>
                    <a href="#">
                        <img src="{{URL::asset($row->options->img)}}" alt=""/>
                        {{ $row->name }}
                    </a>
                    <span class="quantity">  {{ $row->qty }}
                        × Rp. {{ str_replace(',', '.', number_format( $row->price)) }}</span>
                </li>
            @endforeach
    </ul>
    <p class="total">
        <strong>Subtotal:</strong>
        <span class="amount">Rp. {{  Cart::subtotal() }}</span>
    </p>
    <p class="buttons">
        <a href="{{route('carts.index')}}" class="view-cart">Lihat cart</a>
    <!-- {{--  <a href="{{route('checkout')}}" class="checkout">Checkout</a>  --}} -->
    </p>
    @endif
</div>

resources/views/categoryDetail.blade.php
@extends('layouts.app')
@section('content')
<div id="main">
    <div class="section section-bg-10 pt-11 pb-17">
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                @if(!empty($products[0]))
                    <h2 class="page-title text-center">{{$products[0]->categoryName}}</h2>
                @else
                    <h2 class="page-title text-center">Tidak Ada Produk Dalam Kategori Ini :(</h2>
                @endif
                    
                </div>
            </div>
        </div>
    </div>
    <div class="section border-bottom pt-2 pb-2">
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                @if(!empty($products[0]))
                    <ul class="breadcrumbs">
                        <li><a href="{{URL::to('/')}}">Home</a></li>
                        <li><a href="{{route('categories.index')}}">Kategori Produk</a></li>
                        <li>{{$products[0]->categoryName}}</li>
                    </ul>
                @else
                    <ul class="breadcrumbs">
                        <li><a href="{{URL::to('/')}}">Home</a></li>
                        <li><a href="{{route('categories.index')}}">Kategori Produk</a></li>
                    </ul>
                @endif
                </div>
            </div>
        </div>
    </div>
    <div class="section pt-7 pb-7">
        <div class="container">
            <div class="row">
                <div class="col-md-9 col-md-push-3">
                    <div class="shop-filter">
                        <div class="col-md-6">
                            
                        </div>
                        <div class="col-md-6">
                            <div class="shop-filter-right">
                            @if(!empty($products[0]))
                                <form class="commerce-ordering">
                                    <select name="orderby" id="orderby" class="orderby" onchange="catSortBy('{{ $products[0]->category_id }}')">
                                        <option selected="true" disabled="disabled">Urut berdasarkan</option>
                                        <option value="new">Produk baru</option>
                                        <option value="lh">Harga: rendah ke tinggi</option>
                                        <option value="hl">Harga: tinggi ke rendah</option>
                                    </select>
                                </form>
                            @endif
                            </div>
                        </div>
                    </div>
                    <br><br>

                    <div class="product-grid" id="product-grid">
                        {{--<div id="addCart"></div>--}}
                        @if(!empty($products[0]))
                        @foreach($products as $product)
                        <div class="col-md-4 col-sm-6 product-item text-center mb-3">
                            <div class="product-thumb">
                                <a href="{{route('products.show', $product->id)}}">
                                    <div class="badges">
                                        @if($product->best_offer == 'on')
                                            <span class="hot">Best</span>
                                        @else
                                        <!--<span class="hot">Hot</span>
                                                <span class="onsale">Sale!</span>-->
                                        @endif
                                    </div>
                                    @if(!empty($product->image))
                                        <img src="{{URL::asset('/storage/'.$product->image)}}" class="img-thumbnail" style="height: 200px" alt=""/>
                                    @else
                                        <img src="{{URL::asset('/assets/images/test.jpg')}}" class="img-thumbnail" style="height: 200px" alt=""/>
                                    @endif
                                </a>
                                <div class="product-action">
                                    {{--<form>--}}
                                        {{--<input name="id" type="hidden" data-value="{{ $product['id'] }}">--}}
                                        {{--<input name="name" type="hidden" value="{{ $product['name'] }}">--}}
                                        {{--<input name="qty" type="hidden" value="1">--}}
                                        {{--<input name="price" type="hidden" value="{{ $product['price'] }}">--}}
                                        <span class="add-to-cart" style="cursor: pointer" id="btn-addCart" onclick="addCartTemp('{{ $product->id }}','{{ $product->name }}',1,'{{ $product->price }}','{{ $product->image }}')">
													<a data-toggle="tooltip" data-placement="top" title="Tambah ke cart"
                                                       id="btn-addCart" ></a>

												</span>
                                        {{--</form>--}}
                                </div>
                            </div>
                            <div class="product-info">
                                <a href="{{route('products.show', $product->id)}}">
                                    <h2 class="title">{{ $product->name }}</h2>
                                    <span class="price">
													<ins>Rp. {{ str_replace(',', '.', number_format($product->price)) }}</ins>
												</span>
                                </a>
                            </div>
                        </div>
                        @endforeach
                        <div class="col-md-4 col-md-offset-4">
                                {{ $products->appends(request()->input())->links() }}
                        </div> 
                        @else
                        <div class="col-md-8 col-md-offset-2 text-center mb-3">
                        <div class="jumbotron jumbotron-fluid">
                            <div class="container">
                                <h1 class="display-4">Tidak Ada Produk</h1>
                                <p class="lead">Saat ini tidak ada produk dalam kategori ini</p>
                            </div>
                        </div>
                        </div>
                        @endif
                        
                    </div>
                </div>
                <div class="col-md-3 col-md-pull-9">
                    <div class="sidebar">
                        <div class="widget widget-product-search">
                        <div class="form-search">
                            <input type="text" class="search-field" placeholder="Search products…" value="" id="searchProduct"
                               name="s"/>
                            <input type="submit" value="Search" id="searchBtn"/>
                        </div>
                        </div>
                        @if(!empty($products[0]))
                            <div class="widget widget_price_filter">
                                <h3 class="widget-title">Filter berdasarkan harga</h3>
                                <div class="price_slider_wrapper" style="padding-left: 15px; padding-right: 15px;">
                                    <div id="html5"></div>
                                    <div class="price_slider_amount">
                                        <button type="submit" class="button" onclick="filterPriceCategoryProduct('{{$products[0]->category_id}}')">Filter</button>
                                        <div class="price_label" style="display:block;">
                                            {{--IDR <input type="text" id="min_price"/> - IDR <input type="text" id="max_price"/>--}}
                                            IDR <span id="min_price"></span> &mdash; IDR <span id="max_price"></span>
                                        </div>
                                        <div class="clear"></div>
                                    </div>

                                </div>
                            </div>
                        @endif
                        <div class="widget widget-product-categories">
                            <h3 class="widget-title">Kategori Lainnya</h3>
                            <ul class="product-categories">
                                @foreach($countCat as $category)
                                    <li><a href="{{ route('categories.show',$category->id) }}">>&nbsp&nbsp{{ $category->name }}</a></li>
                                @endforeach
                            </ul>
                        </div>


                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@push('scripts')
    <script type="text/javascript">

        var html5Slider = document.getElementById('html5');
        if(html5Slider){
            noUiSlider.create(html5Slider, {
                start: [ 0, 50000 ],
                connect: true,
                range: {
                    'min': 0,
                    'max': 50000
                },
                format: wNumb({
                    decimals: 0,
                })
            });

            var snapValues = [
                document.getElementById('min_price'),
                document.getElementById('max_price')
            ];
            html5Slider.noUiSlider.on('update', function( values, handle ) {
                snapValues[handle].innerHTML = values[handle];
            });
        }




    </script>
@endpush

resources/views/customer-service.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: robseptian
 * Date: 05/01/18
 * Time: 19.56
 */
?>
@extends('layouts.app')
@section('content')
    <div id="main">
        <div class="section section-bg-10 pt-11 pb-17">
            <div class="container">
                <div class="row">
                    <div class="col-sm-12">
                        <h2 class="page-title text-center">Customer Service</h2>
                    </div>
                </div>
            </div>
        </div>
        <div class="section border-bottom pt-2 pb-2">
            <div class="container">
                <div class="row">
                    <div class="col-sm-12">
                        <ul class="breadcrumbs">
                            <li><a href="{{URL::to('/')}}">Home</a></li>
                            <li>Customer Service</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="section pt-7 pb-7">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="single-blog">
                            <div class="entry-content">
                                {!! $cs[0]->body !!}
                            </div>
                            <!-- <div class="entry-footer">
                                <div class="row">

                                    <div class="col-md-12">
                                        <div class="share">
                                            <span> <i class="ion-android-share-alt"></i> Share this post </span>
                                            <span> <a target="_blank" href="#"><i class="fa fa-facebook"></i></a> </span>
                                            <span> <a target="_blank" href="#"><i class="fa fa-twitter"></i></a> </span>
                                            <span> <a target="_blank" href="#"><i class="fa fa-google-plus"></i></a> </span>
                                        </div>
                                    </div>
                                </div>
                            </div> -->

                            <!-- <div class="entry-nav">
                                <div class="row">
                                    <div class="col-md-5 left">
                                        <i class="fa fa-angle-double-left"></i>
                                        <a href="#">How can salmon be raised organically in fish farms?</a>
                                    </div>
                                    <div class="col-md-2 text-center">
                                        <i class="ion-grid"></i>
                                    </div>
                                    <div class="col-md-5 right">
                                        <a href="#">How to steam &amp; purée your sugar pie pumkin</a>
                                        <i class="fa fa-angle-double-right"></i>
                                    </div>
                                </div>
                            </div> -->

                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/disable.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: najibalkhala
 * Date: 3/3/2018
 * Time: 5:06 PM
 */
?>
@extends('layouts.app')
@section('content')
    <div id="main">
        <div class="section section-error pt-12 pb-12">
            <div class="container">
                <div class="row">
                    <div class="col-sm-12">
                        <div class="text-center">
                            <img src="{{URL::asset('/assets/images/disable.png')}}" class="mb-6" alt=""/>
                            <h3 class="error-title uppercase">Oops! situs ini tidak tesedia!</h3>
                            <h1 class="error-title uppercase">
                                Segera selesaikan pembayaran anda untuk dapat membukanya :)
                            </h1>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/partner-petaniDetail.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: robseptian
 * Date: 05/01/18
 * Time: 19.56
 */
?>
@extends('layouts.app')
@section('content')
    <div id="main">
        <div class="section border-bottom pt-2 pb-2">
            <div class="container">
                <div class="row">
                    <div class="col-sm-12">
                        <ul class="breadcrumbs">
                            <li><a href="{{URL::to('/')}}">Home</a></li>
                            <li><a href="{{route('suppliers.index')}}">Partner Petani</a></li>
                            <li>{{$supplier->name}}</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="section pt-2 pb-7">
            <div class="container">
                <div class="row">
                    <div class="col-md-6 col-md-offset-5">
                        <h2>{{$supplier->name}}</h2>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-3">
                        @if(!empty($supplier->image))
                            <img src="{{URL::asset('/storage/'.$supplier->image)}}" class="img-thumbnail" style="height: 230px">
                        @else
                            <img src="{{URL::asset('/assets/images/test.jpg')}}" class="img-thumbnail" style="height: 230px"/>
                        @endif

                    </div>
                    <div class="col-md-9">
                    {!! $supplier->description !!}
                    </div>

                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/shippDetail.blade.php
<table>
                                <tbody>
                                <tr class="cart-subtotal">
                                    <th colspan="2">Subtotal</th>
                                    <td id="loading">Rp. <?php echo Cart::subtotal(); ?></td>
                                </tr>
                                <tr class="shipping">
                                    <th>Shipping</th>
                                    @if(empty ( $shipping ))
                                        <td>Choose Delivery Address</td>
                                        @else
                                        <th id="dstLoading">{{$addresses[0]->distance/1000}} Km</th>
                                        <td id="shippingLoading">Rp. {{ str_replace(',', '.', number_format($shipping)) }}</td>
                                    @endif

                                </tr>
                                <tr class="order-total">
                                    <th colspan="2">Total</th>
                                    @if(empty ( $shipping ))
                                        <td>----</td>
                                    @else
                                        <td id="totalShippingLoading"><strong>Rp. {{ str_replace(',', '.', number_format($total)) }}</strong></td>
                                    @endif

                                </tr>
                                </tbody>
                            </table>